package cz.muni.fi.pa165.enums;

/**
 * Created by vojta on 10/25/16.
 */
public enum GHOST_ABILITIES {
    FLIGHT,INTANGIBILITY,INVISIBILITY,OVERSHADOWING,GHOST_RAY,SUPERNATURAL_PHYSICAL_ABILITIES,GOING_GHOST,
    GHOSTLY_WAIL,DUPLICATION,TELEPORTATION,CRYOKINESIS,SHAPE_SHIFTING,TELEKINESIS,
    SIZE_CHANGING,GHOST_PORTAL_CREATION,GHOST_SHIELD,GHOST_STINGER
}
